project_name: ingress-rule
release:
  github:
    owner: pragaonj
    name: ingress-rule-updater
builds:
  - id: ingress-rule
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    main: cmd/ingress-rule/main.go
    ldflags: -s -w
      -X github.com/pragaonj/ingress-rule-updater/cmd/ingress-rule/cli.version=
archives:
  - id: ingress-rule
    builds:
    - ingress-rule
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
