apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: ingress-rule
spec:
  version: {{ .TagName }}
  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/pragaonj/ingress-rule-updater/releases/download/{{ .TagName }}/ingress-rule_{{ .TagName }}_linux_amd64.tar.gz" .TagName | indent 6 }}
      files:
        - from: "./ingress-rule"
          to: "."
        - from: LICENSE
          to: "."
      bin: "ingress-rule"
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/pragaonj/ingress-rule-updater/releases/download/{{ .TagName }}/ingress-rule_{{ .TagName }}_darwin_amd64.tar.gz" .TagName | indent 6 }}
      files:
        - from: "./ingress-rule"
          to: "."
        - from: LICENSE
          to: "."
      bin: "ingress-rule"
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/pragaonj/ingress-rule-updater/releases/download/{{ .TagName }}/ingress-rule_{{ .TagName }}_darwin_arm64.tar.gz" .TagName | indent 6 }}
      files:
        - from: "./ingress-rule"
          to: "."
        - from: LICENSE
          to: "."
      bin: "ingress-rule"
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/pragaonj/ingress-rule-updater/releases/download/{{ .TagName }}/ingress-rule_{{ .TagName }}_windows_amd64.zip" .TagName | indent 6 }}
      files:
        - from: "/ingress-rule.exe"
          to: "."
        - from: LICENSE
          to: "."
      bin: "ingress-rule.exe"
  shortDescription: Update Ingress rules via command line
  homepage: https://github.com/pragaonj/ingress-rule-updater
  description: |
    Add/remove rules to/from a Kubernetes Ingress via command line.
    This plugin allows the configuration of an Ingress resource with command line arguments.
    
    When adding/deleting a backend rule the Ingress will be updated.
    On creation of a rule for a non-existing Ingress name a new Ingress will be created.
    If the last rule is deleted the Ingress will be deleted as well.
