apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: ingress-rule
spec:
  version: "v0.1.0"
  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/pragaonj/ingress-rule-updater/releases/download/v0.1.0/ingress-rule_linux_amd64.tar.gz
      sha256: ""
      files:
        - from: "./ingress-rule"
          to: "."
        - from: LICENSE
          to: "."
      bin: "ingress-rule"
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/pragaonj/ingress-rule-updater/releases/download/v0.1.0/ingress-rule_darwin_amd64.tar.gz
      sha256: ""
      files:
        - from: "./ingress-rule"
          to: "."
        - from: LICENSE
          to: "."
      bin: "ingress-rule"
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/pragaonj/ingress-rule-updater/releases/download/v0.1.0/ingress-rule_windows_amd64.zip
      sha256: ""
      files:
        - from: "/ingress-rule.exe"
          to: "."
        - from: LICENSE
          to: "."
      bin: "ingress-rule.exe"
  shortDescription: Update ingress rules via command line.
  homepage: https://github.com/pragaonj/ingress-rule-updater
  description: |
    Add/remove rules to/from a kubernetes ingress via command line.
    This plugin allows the configuration of an ingress resource with command line arguments.
    
    When adding/deleting a backend rule the ingress will be updated.
    On creation of a rule for a non-existing ingress name a new ingress will be created.
    If the last rule is deleted the ingress will be deleted as well.
